apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}-deployment
  labels:
{{- include "zur.labels" . | nindent 4 }}
spec:
{{- if not .Values.client.autoscaling.enabled }}
  replicas: {{ .Values.client.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      component: {{ .Values.client.component }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
        component: {{ .Values.client.component }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "zur.serviceAccountName" . }}
      securityContext:
{{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
{{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.client.image.name }}:{{ .Values.client.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.client.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
