apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.client.name }}-rollout
  labels:
    {{- include "zur.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.client.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.client.component }}
    spec:
      serviceAccountName: {{ include "zur.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.client.image.name }}:{{ .Values.client.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.client.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  strategy:
    canary:
      steps:
        - setWeight: 10
          analysis:
            templates:
              - name: basic-check
          pause:
            duration: 1m
        - setWeight: 50
          analysis:
            templates:
              - name: common-check
          pause:
            duration: 1m

---

apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: basic-check
spec:
  metrics:
    - name: latency
      interval: 1m
      provider:
        mock:
          value: 800  # Set a fixed value for testing purposes (e.g., 800 milliseconds)
      successCondition: result[0] < 1000
      failureCondition: result[0] >= 1000
  args:
    - name: service-name
      value: "{{ .Release.Name }}"
