apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.client.name }}
spec:
  maxUnavailable: {{ .Values.pdbClient.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.client.name }}
