apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.server.name }}
spec:
  maxUnavailable: {{ .Values.pdbServer.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.server.name }}
