apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}-deployment
  labels:
    {{- include "zur.labels" . | nindent 4 }}
spec:
  {{- if not .Values.client.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicas }}
  {{- end }}
  selector:
    matchLabels:
      component: {{ .Values.worker.selector.matchLabels.component }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        component: {{ .Values.worker.template.metadata.labels.component }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zur.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.worker.repository }}:{{ .Values.worker.repository_tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $env := .Values.worker.template.spec.containers }}
            {{- range $var := $env.env }}
            - name: {{ $var.name | quote }}
              value: {{ $var.value | quote }}
            {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
