apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zur.fullname" . }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zur.name" . }}
