name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main 
  pull_request:
    paths:
      - 'webapp/**'
    
  
jobs:
  helm_template:
    name: Helm Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
       ref: ${{ github.event.pull_request.head.sha }}


    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Lint Helm Chart
      run: |
        helm lint ./webapp --values ./webapp/env/values-prod.yaml
        if [ $? -ne 0 ]; then
          echo "Error in Helm lint"
          exit 1
        else
          echo "Lint is successful"  
        fi
      
    - name: Helm Template
      run: |
        helm template ./webapp --values ./webapp/env/values-prod.yaml
        if [ $? -ne 0 ]; then
          echo "Error in helm template"
          exit 1
        else
          echo "Helm Chart is good"
          exit 0
        fi


