# on comment
# git checkout 
# set up tf
# gcloud authenticate - use secrets
# tf init
# if comment contains "terraform apply" , trigger terraform apply -auto-approve with no inputs flag
# if apply fails, fail the action.


# after all, create branch protection rule - that only if ci and tf-plan works, you can merge an pull request

name: tf-apply

on:
  issue_comment:
    types:
      - created

jobs:
  terraform:
    runs-on: ubuntu-latest

    if: (contains(github.event.comment.body, 'terraform apply') && github.event.issue.pull_request)
    steps:
     

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Terraform Apply
      run: |
          terraform apply -auto-approve -no-color -var-file=terraform.tfvars
      working-directory: tf
