name: Terraform Apply

on: [issue_comment]
  

jobs:
  apply:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/terraform apply') }}
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Authenticate with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2 
          

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: tf
          auto_approve: true
