# "on" step - only in tf folder, on all pr
# git checkout 
# set up tf
# gcloud authenticate - use secrets
# tf init
#tf plan 
# output plan as comment
# fail action if plan failed
name: Terraform Plan

on:
  pull_request:
    paths:
      - 'tf/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2 

    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'


    - name: Initialize Terraform
      run: terraform init
      if: github.event_name == 'pull_request'

    - name: Terraform Plan
      run: |
        terraform plan -out=tfplan
        if [ $? -ne 0 ]; then
          echo "Terraform plan failed."
          exit 1
        fi
      if: github.event_name == 'pull_request'

    - name: Comment with Terraform Plan
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const planContent = fs.readFileSync('tfplan', 'utf8');
          const planComment = '```terraform\n' + planContent + '\n```';
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Terraform Plan:\n' + planComment
          });
      if: github.event_name == 'pull_request'
